//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 06:46:51 AM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://esmt.sn/gesb/soam", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sn.esmt.gesb.soam;
