version: "3.8"
services:
  tpo_manager:
    image: olakouns/app-tpo:v1.5
    ports:
      - 8090:8090
    networks:
      - springapimysql8
    environment:
      DATABASE_URL: mysqldb2:3306
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "mot2P@ss"
    depends_on:
      - mysqldb2
    volumes:
      - .m2:/root/.m3
  mysqldb2:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    networks:
      - springapimysql8
    environment:
      MYSQL_DATABASE: tpo_db
      MYSQL_USER: olakouns
      MYSQL_PASSWORD: "mot2P@ss"
      MYSQL_ROOT_PASSWORD: "mot2P@ss"
    volumes:
      - db2:/var/lib/mysql8
networks:
  springapimysql8:
volumes:
  db2: