apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpo-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-tpo
  template:
    metadata:
      labels:
        app: app-tpo
    spec:
      containers:
        - name: app-tpo-container
          image: your-registry/app-b:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "db-service:3306"
            - name: SERVER_PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: app-tpo-loadbalancer
spec:
  selector:
    app: app-tpo
  ports:
    - protocol: TCP
      port: 8090  # Port externe pour l'application B
      targetPort: 8080  # Port interne sur lequel l'application B écoute
  type: LoadBalancer