//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 12:43:23 PM GMT 
//


package sn.esmt.in_api.soam;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subscriberName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="imsi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataBalance" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="callBalance" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="smsBalance" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subscriberName",
    "phoneNumber",
    "imsi",
    "dataBalance",
    "callBalance",
    "smsBalance"
})
@XmlRootElement(name = "displaySubscriberResponse")
public class DisplaySubscriberResponse {

    @XmlElement(required = true)
    protected String subscriberName;
    @XmlElement(required = true)
    protected String phoneNumber;
    @XmlElement(required = true)
    protected String imsi;
    protected double dataBalance;
    protected double callBalance;
    protected double smsBalance;

    /**
     * Gets the value of the subscriberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberName() {
        return subscriberName;
    }

    /**
     * Sets the value of the subscriberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberName(String value) {
        this.subscriberName = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImsi(String value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the dataBalance property.
     * 
     */
    public double getDataBalance() {
        return dataBalance;
    }

    /**
     * Sets the value of the dataBalance property.
     * 
     */
    public void setDataBalance(double value) {
        this.dataBalance = value;
    }

    /**
     * Gets the value of the callBalance property.
     * 
     */
    public double getCallBalance() {
        return callBalance;
    }

    /**
     * Sets the value of the callBalance property.
     * 
     */
    public void setCallBalance(double value) {
        this.callBalance = value;
    }

    /**
     * Gets the value of the smsBalance property.
     * 
     */
    public double getSmsBalance() {
        return smsBalance;
    }

    /**
     * Sets the value of the smsBalance property.
     * 
     */
    public void setSmsBalance(double value) {
        this.smsBalance = value;
    }

}
