//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.22 at 12:43:23 PM GMT 
//


package sn.esmt.in_api.soam;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sn.esmt.in_api.soam package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewConnectionResponse_QNAME = new QName("http://esmt.sn/in_api/soam", "newConnectionResponse");
    private final static QName _RechargingResponse_QNAME = new QName("http://esmt.sn/in_api/soam", "rechargingResponse");
    private final static QName _TerminationResponse_QNAME = new QName("http://esmt.sn/in_api/soam", "terminationResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sn.esmt.in_api.soam
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewConnectionRequest }
     * 
     */
    public NewConnectionRequest createNewConnectionRequest() {
        return new NewConnectionRequest();
    }

    /**
     * Create an instance of {@link ApiResponse }
     * 
     */
    public ApiResponse createApiResponse() {
        return new ApiResponse();
    }

    /**
     * Create an instance of {@link RechargingRequest }
     * 
     */
    public RechargingRequest createRechargingRequest() {
        return new RechargingRequest();
    }

    /**
     * Create an instance of {@link TerminationRequest }
     * 
     */
    public TerminationRequest createTerminationRequest() {
        return new TerminationRequest();
    }

    /**
     * Create an instance of {@link DisplaySubscriberRequest }
     * 
     */
    public DisplaySubscriberRequest createDisplaySubscriberRequest() {
        return new DisplaySubscriberRequest();
    }

    /**
     * Create an instance of {@link DisplaySubscriberResponse }
     * 
     */
    public DisplaySubscriberResponse createDisplaySubscriberResponse() {
        return new DisplaySubscriberResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ApiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://esmt.sn/in_api/soam", name = "newConnectionResponse")
    public JAXBElement<ApiResponse> createNewConnectionResponse(ApiResponse value) {
        return new JAXBElement<ApiResponse>(_NewConnectionResponse_QNAME, ApiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ApiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://esmt.sn/in_api/soam", name = "rechargingResponse")
    public JAXBElement<ApiResponse> createRechargingResponse(ApiResponse value) {
        return new JAXBElement<ApiResponse>(_RechargingResponse_QNAME, ApiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApiResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ApiResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://esmt.sn/in_api/soam", name = "terminationResponse")
    public JAXBElement<ApiResponse> createTerminationResponse(ApiResponse value) {
        return new JAXBElement<ApiResponse>(_TerminationResponse_QNAME, ApiResponse.class, null, value);
    }

}
