//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 04:34:57 PM GMT 
//


package sn.esmt.in_api.soam;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataBalance" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="callBalance" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="smsBalance" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="phoneNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataBalance",
    "callBalance",
    "smsBalance"
})
@XmlRootElement(name = "rechargingRequest")
public class RechargingRequest {

    protected double dataBalance;
    protected double callBalance;
    protected double smsBalance;
    @XmlAttribute(name = "phoneNumber", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String phoneNumber;

    /**
     * Gets the value of the dataBalance property.
     * 
     */
    public double getDataBalance() {
        return dataBalance;
    }

    /**
     * Sets the value of the dataBalance property.
     * 
     */
    public void setDataBalance(double value) {
        this.dataBalance = value;
    }

    /**
     * Gets the value of the callBalance property.
     * 
     */
    public double getCallBalance() {
        return callBalance;
    }

    /**
     * Sets the value of the callBalance property.
     * 
     */
    public void setCallBalance(double value) {
        this.callBalance = value;
    }

    /**
     * Gets the value of the smsBalance property.
     * 
     */
    public double getSmsBalance() {
        return smsBalance;
    }

    /**
     * Sets the value of the smsBalance property.
     * 
     */
    public void setSmsBalance(double value) {
        this.smsBalance = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

}
