apiVersion: v1
kind: Service
metadata:
  name: app-mysql-in
  labels:
    app: db-app-in
spec:
  ports:
    - port: 3307
      targetPort: 3307
  selector:
    app: db-app-in
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-in
  labels:
    app: db-app-in
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mysql-in
  labels:
    app: db-app-in
spec:
  selector:
    matchLabels:
      app: db-app-in
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-app-in
        tier: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-database-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-user-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3307
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage-in
              mountPath: /var/lib/mysql2
      volumes:
        - name: mysql-persistent-storage-in
          persistentVolumeClaim:
            claimName: mysql-pvc-in