apiVersion: v1
kind: Service
metadata:
  name: app-mysql-hlr
  labels:
    app: db-app-hlr
spec:
  ports:
    - port: 3308
      targetPort: 3308
  selector:
    app: db-app-hlr
    tier: mysql-hlr
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-hlr
  labels:
    app: db-app-hlr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-mysql-hlr
  labels:
    app: db-app-hlr
spec:
  selector:
    matchLabels:
      app: db-app-hlr
      tier: mysql-hlr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-app-hlr
        tier: mysql-hlr
    spec:
      containers:
        - image: mysql:latest
          name: mysql-hlr
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-database-hlr-name
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: mysql-user-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: mysql-user-password
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3308
              name: mysql-hlr
          volumeMounts:
            - name: mysql-persistent-storage-hlr
              mountPath: /var/lib/mysql-hlr
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: mysql-persistent-storage-hlr
          persistentVolumeClaim:
            claimName: mysql-pvc-hlr