//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.18 at 12:30:01 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://esmt.sn/hlr_api/soam", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sn.esmt.hlr_api.soam;
