//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 04:34:55 PM GMT 
//


package sn.esmt.gesb.soam;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sn.esmt.gesb.soam package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sn.esmt.gesb.soam
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EsbRootActionResponse }
     * 
     */
    public EsbRootActionResponse createEsbRootActionResponse() {
        return new EsbRootActionResponse();
    }

    /**
     * Create an instance of {@link EsbRootActionRequest }
     * 
     */
    public EsbRootActionRequest createEsbRootActionRequest() {
        return new EsbRootActionRequest();
    }

    /**
     * Create an instance of {@link EsbContent }
     * 
     */
    public EsbContent createEsbContent() {
        return new EsbContent();
    }

    /**
     * Create an instance of {@link EsbParameter }
     * 
     */
    public EsbParameter createEsbParameter() {
        return new EsbParameter();
    }

    /**
     * Create an instance of {@link EsbServices }
     * 
     */
    public EsbServices createEsbServices() {
        return new EsbServices();
    }

    /**
     * Create an instance of {@link EsbService }
     * 
     */
    public EsbService createEsbService() {
        return new EsbService();
    }

}
