version: "3.8"
services:
  tpo_manager:
    image: olakouns/app-in:latest
    restart: on-failure
    ports:
      - 8091:8091
    networks:
      - in_api_network
    environment:
      DB_SERVER: mysqldb
      DB_PORT: 3306
      DB_NAME: in_api_db
      DB_USERNAME: "root"
      DB_PASSWORD: "mot2P@ss"
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m3
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    networks:
      - in_api_network
    environment:
      MYSQL_DATABASE: in_api_db
      MYSQL_USER: olakouns
      MYSQL_PASSWORD: "mot2P@ss"
      MYSQL_ROOT_PASSWORD: "mot2P@ss"
    volumes:
      - in_db:/var/lib/mysql_in_api
networks:
  in_api_network:
volumes:
  in_db: